package com.gfxy.common.portal.dao;

import com.gfxy.common.portal.entity.AppButton;
import com.gfxy.common.portal.entity.AppButtonExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AppButtonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_BUTTON
     *
     * @mbggenerated Fri May 17 22:25:33 CST 2019
     */
    int countByExample(AppButtonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_BUTTON
     *
     * @mbggenerated Fri May 17 22:25:33 CST 2019
     */
    int deleteByExample(AppButtonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_BUTTON
     *
     * @mbggenerated Fri May 17 22:25:33 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_BUTTON
     *
     * @mbggenerated Fri May 17 22:25:33 CST 2019
     */
    int insert(AppButton record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_BUTTON
     *
     * @mbggenerated Fri May 17 22:25:33 CST 2019
     */
    int insertSelective(AppButton record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_BUTTON
     *
     * @mbggenerated Fri May 17 22:25:33 CST 2019
     */
    List<AppButton> selectByExample(AppButtonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_BUTTON
     *
     * @mbggenerated Fri May 17 22:25:33 CST 2019
     */
    AppButton selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_BUTTON
     *
     * @mbggenerated Fri May 17 22:25:33 CST 2019
     */
    int updateByExampleSelective(@Param("record") AppButton record, @Param("example") AppButtonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_BUTTON
     *
     * @mbggenerated Fri May 17 22:25:33 CST 2019
     */
    int updateByExample(@Param("record") AppButton record, @Param("example") AppButtonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_BUTTON
     *
     * @mbggenerated Fri May 17 22:25:33 CST 2019
     */
    int updateByPrimaryKeySelective(AppButton record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_BUTTON
     *
     * @mbggenerated Fri May 17 22:25:33 CST 2019
     */
    int updateByPrimaryKey(AppButton record);

    List<AppButton> getRoleBtnList(String userName, String menuId);
}