package com.gfxy.common.portal.dao;

import com.gfxy.common.portal.entity.Organization;
import com.gfxy.common.portal.entity.OrganizationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrganizationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORGANIZATION
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    int countByExample(OrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORGANIZATION
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    int deleteByExample(OrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORGANIZATION
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    int deleteByPrimaryKey(String organizationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORGANIZATION
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    int insert(Organization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORGANIZATION
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    int insertSelective(Organization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORGANIZATION
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    List<Organization> selectByExample(OrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORGANIZATION
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    Organization selectByPrimaryKey(String organizationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORGANIZATION
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    int updateByExampleSelective(@Param("record") Organization record, @Param("example") OrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORGANIZATION
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    int updateByExample(@Param("record") Organization record, @Param("example") OrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORGANIZATION
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    int updateByPrimaryKeySelective(Organization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORGANIZATION
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    int updateByPrimaryKey(Organization record);
}