package com.gfxy.common.portal.dao;

import com.gfxy.common.portal.entity.Role;
import com.gfxy.common.portal.entity.RoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    int countByExample(RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    int deleteByExample(RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    int deleteByPrimaryKey(String roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    int insertSelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    List<Role> selectByExample(RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    Role selectByPrimaryKey(String roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    int updateByExampleSelective(@Param("record") Role record, @Param("example") RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    int updateByExample(@Param("record") Role record, @Param("example") RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    int updateByPrimaryKeySelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    int updateByPrimaryKey(Role record);
}