package com.gfxy.common.portal.dao;

import com.gfxy.common.portal.entity.Staff;
import com.gfxy.common.portal.entity.StaffExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StaffMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAFF
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    int countByExample(StaffExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAFF
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    int deleteByExample(StaffExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAFF
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    int deleteByPrimaryKey(String staffId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAFF
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    int insert(Staff record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAFF
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    int insertSelective(Staff record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAFF
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    List<Staff> selectByExample(StaffExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAFF
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    Staff selectByPrimaryKey(String staffId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAFF
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    int updateByExampleSelective(@Param("record") Staff record, @Param("example") StaffExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAFF
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    int updateByExample(@Param("record") Staff record, @Param("example") StaffExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAFF
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    int updateByPrimaryKeySelective(Staff record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAFF
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    int updateByPrimaryKey(Staff record);
}