package com.gfxy.common.portal.entity;

public class AppButton {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_BUTTON.ID
     *
     * @mbggenerated Fri May 17 22:25:33 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_BUTTON.APP_ID
     *
     * @mbggenerated Fri May 17 22:25:33 CST 2019
     */
    private String appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_BUTTON.BTN_ID
     *
     * @mbggenerated Fri May 17 22:25:33 CST 2019
     */
    private String btnId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_BUTTON.BTN_NAME
     *
     * @mbggenerated Fri May 17 22:25:33 CST 2019
     */
    private String btnName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_BUTTON.ID
     *
     * @return the value of APP_BUTTON.ID
     *
     * @mbggenerated Fri May 17 22:25:33 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_BUTTON.ID
     *
     * @param id the value for APP_BUTTON.ID
     *
     * @mbggenerated Fri May 17 22:25:33 CST 2019
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_BUTTON.APP_ID
     *
     * @return the value of APP_BUTTON.APP_ID
     *
     * @mbggenerated Fri May 17 22:25:33 CST 2019
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_BUTTON.APP_ID
     *
     * @param appId the value for APP_BUTTON.APP_ID
     *
     * @mbggenerated Fri May 17 22:25:33 CST 2019
     */
    public void setAppId(String appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_BUTTON.BTN_ID
     *
     * @return the value of APP_BUTTON.BTN_ID
     *
     * @mbggenerated Fri May 17 22:25:33 CST 2019
     */
    public String getBtnId() {
        return btnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_BUTTON.BTN_ID
     *
     * @param btnId the value for APP_BUTTON.BTN_ID
     *
     * @mbggenerated Fri May 17 22:25:33 CST 2019
     */
    public void setBtnId(String btnId) {
        this.btnId = btnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_BUTTON.BTN_NAME
     *
     * @return the value of APP_BUTTON.BTN_NAME
     *
     * @mbggenerated Fri May 17 22:25:33 CST 2019
     */
    public String getBtnName() {
        return btnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_BUTTON.BTN_NAME
     *
     * @param btnName the value for APP_BUTTON.BTN_NAME
     *
     * @mbggenerated Fri May 17 22:25:33 CST 2019
     */
    public void setBtnName(String btnName) {
        this.btnName = btnName;
    }
}