package com.gfxy.common.portal.entity;

public class AppTree {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_TREE.ID
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_TREE.NAME
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_TREE.LABEL
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    private String label;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_TREE.URL
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_TREE.NOTES
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    private String notes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_TREE.ORDER_NUM
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    private Integer orderNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_TREE.PARENT_ID
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    private String parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_TREE.IS_LEAF
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    private Integer isLeaf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_TREE.ICON_CLS
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    private String iconCls;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_TREE.DISABLED
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    private Integer disabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_TREE.OPEN_TYPE
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    private Integer openType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_TREE.LEVEL_NUM
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    private Integer levelNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_TREE.RELATING_ID
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    private String relatingId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_TREE.ID
     *
     * @return the value of APP_TREE.ID
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_TREE.ID
     *
     * @param id the value for APP_TREE.ID
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_TREE.NAME
     *
     * @return the value of APP_TREE.NAME
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_TREE.NAME
     *
     * @param name the value for APP_TREE.NAME
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_TREE.LABEL
     *
     * @return the value of APP_TREE.LABEL
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public String getLabel() {
        return label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_TREE.LABEL
     *
     * @param label the value for APP_TREE.LABEL
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public void setLabel(String label) {
        this.label = label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_TREE.URL
     *
     * @return the value of APP_TREE.URL
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_TREE.URL
     *
     * @param url the value for APP_TREE.URL
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_TREE.NOTES
     *
     * @return the value of APP_TREE.NOTES
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_TREE.NOTES
     *
     * @param notes the value for APP_TREE.NOTES
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public void setNotes(String notes) {
        this.notes = notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_TREE.ORDER_NUM
     *
     * @return the value of APP_TREE.ORDER_NUM
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public Integer getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_TREE.ORDER_NUM
     *
     * @param orderNum the value for APP_TREE.ORDER_NUM
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_TREE.PARENT_ID
     *
     * @return the value of APP_TREE.PARENT_ID
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_TREE.PARENT_ID
     *
     * @param parentId the value for APP_TREE.PARENT_ID
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_TREE.IS_LEAF
     *
     * @return the value of APP_TREE.IS_LEAF
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public Integer getIsLeaf() {
        return isLeaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_TREE.IS_LEAF
     *
     * @param isLeaf the value for APP_TREE.IS_LEAF
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public void setIsLeaf(Integer isLeaf) {
        this.isLeaf = isLeaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_TREE.ICON_CLS
     *
     * @return the value of APP_TREE.ICON_CLS
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public String getIconCls() {
        return iconCls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_TREE.ICON_CLS
     *
     * @param iconCls the value for APP_TREE.ICON_CLS
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public void setIconCls(String iconCls) {
        this.iconCls = iconCls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_TREE.DISABLED
     *
     * @return the value of APP_TREE.DISABLED
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public Integer getDisabled() {
        return disabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_TREE.DISABLED
     *
     * @param disabled the value for APP_TREE.DISABLED
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public void setDisabled(Integer disabled) {
        this.disabled = disabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_TREE.OPEN_TYPE
     *
     * @return the value of APP_TREE.OPEN_TYPE
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public Integer getOpenType() {
        return openType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_TREE.OPEN_TYPE
     *
     * @param openType the value for APP_TREE.OPEN_TYPE
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public void setOpenType(Integer openType) {
        this.openType = openType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_TREE.LEVEL_NUM
     *
     * @return the value of APP_TREE.LEVEL_NUM
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public Integer getLevelNum() {
        return levelNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_TREE.LEVEL_NUM
     *
     * @param levelNum the value for APP_TREE.LEVEL_NUM
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public void setLevelNum(Integer levelNum) {
        this.levelNum = levelNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_TREE.RELATING_ID
     *
     * @return the value of APP_TREE.RELATING_ID
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public String getRelatingId() {
        return relatingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_TREE.RELATING_ID
     *
     * @param relatingId the value for APP_TREE.RELATING_ID
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public void setRelatingId(String relatingId) {
        this.relatingId = relatingId;
    }

    @Override
    public String toString() {
        return "AppTree{" +
                "id='" + id + '\'' +
                ", name='" + name + '\'' +
                ", label='" + label + '\'' +
                ", url='" + url + '\'' +
                ", notes='" + notes + '\'' +
                ", orderNum=" + orderNum +
                ", parentId='" + parentId + '\'' +
                ", isLeaf=" + isLeaf +
                ", iconCls='" + iconCls + '\'' +
                ", disabled=" + disabled +
                ", openType=" + openType +
                ", levelNum=" + levelNum +
                ", relatingId='" + relatingId + '\'' +
                '}';
    }
}