package com.gfxy.common.portal.entity;

import java.util.Date;

public class Organization {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORGANIZATION.ORGANIZATION_ID
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    private String organizationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORGANIZATION.DESCRIPTION
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORGANIZATION.NAME
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORGANIZATION.NODE_LEVEL
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    private Integer nodeLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORGANIZATION.PARENT_ID
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    private String parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORGANIZATION.STATE
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORGANIZATION.UPDATE_TIME
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORGANIZATION.UPDATE_USER
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    private String updateUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORGANIZATION.ORGANIZATION_ID
     *
     * @return the value of ORGANIZATION.ORGANIZATION_ID
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public String getOrganizationId() {
        return organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORGANIZATION.ORGANIZATION_ID
     *
     * @param organizationId the value for ORGANIZATION.ORGANIZATION_ID
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public void setOrganizationId(String organizationId) {
        this.organizationId = organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORGANIZATION.DESCRIPTION
     *
     * @return the value of ORGANIZATION.DESCRIPTION
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORGANIZATION.DESCRIPTION
     *
     * @param description the value for ORGANIZATION.DESCRIPTION
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORGANIZATION.NAME
     *
     * @return the value of ORGANIZATION.NAME
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORGANIZATION.NAME
     *
     * @param name the value for ORGANIZATION.NAME
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORGANIZATION.NODE_LEVEL
     *
     * @return the value of ORGANIZATION.NODE_LEVEL
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public Integer getNodeLevel() {
        return nodeLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORGANIZATION.NODE_LEVEL
     *
     * @param nodeLevel the value for ORGANIZATION.NODE_LEVEL
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public void setNodeLevel(Integer nodeLevel) {
        this.nodeLevel = nodeLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORGANIZATION.PARENT_ID
     *
     * @return the value of ORGANIZATION.PARENT_ID
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORGANIZATION.PARENT_ID
     *
     * @param parentId the value for ORGANIZATION.PARENT_ID
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORGANIZATION.STATE
     *
     * @return the value of ORGANIZATION.STATE
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORGANIZATION.STATE
     *
     * @param state the value for ORGANIZATION.STATE
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORGANIZATION.UPDATE_TIME
     *
     * @return the value of ORGANIZATION.UPDATE_TIME
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORGANIZATION.UPDATE_TIME
     *
     * @param updateTime the value for ORGANIZATION.UPDATE_TIME
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORGANIZATION.UPDATE_USER
     *
     * @return the value of ORGANIZATION.UPDATE_USER
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORGANIZATION.UPDATE_USER
     *
     * @param updateUser the value for ORGANIZATION.UPDATE_USER
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }


    @Override
    public String toString() {
        return "Organization{" +
                "organizationId='" + organizationId + '\'' +
                ", description='" + description + '\'' +
                ", name='" + name + '\'' +
                ", nodeLevel=" + nodeLevel +
                ", parentId='" + parentId + '\'' +
                ", state=" + state +
                ", updateTime=" + updateTime +
                ", updateUser='" + updateUser + '\'' +
                '}';
    }
}