package com.gfxy.common.portal.entity;

import java.util.Date;

public class Role {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROLE.ROLE_ID
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROLE.NAME
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROLE.STATE
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROLE.UPDATE_TIME
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROLE.UPDATE_USER
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROLE.SYSTEM_ID
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    private String systemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROLE.DESCRIPTION
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROLE.ROLE_ID
     *
     * @return the value of ROLE.ROLE_ID
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROLE.ROLE_ID
     *
     * @param roleId the value for ROLE.ROLE_ID
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROLE.NAME
     *
     * @return the value of ROLE.NAME
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROLE.NAME
     *
     * @param name the value for ROLE.NAME
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROLE.STATE
     *
     * @return the value of ROLE.STATE
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROLE.STATE
     *
     * @param state the value for ROLE.STATE
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROLE.UPDATE_TIME
     *
     * @return the value of ROLE.UPDATE_TIME
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROLE.UPDATE_TIME
     *
     * @param updateTime the value for ROLE.UPDATE_TIME
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROLE.UPDATE_USER
     *
     * @return the value of ROLE.UPDATE_USER
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROLE.UPDATE_USER
     *
     * @param updateUser the value for ROLE.UPDATE_USER
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROLE.SYSTEM_ID
     *
     * @return the value of ROLE.SYSTEM_ID
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public String getSystemId() {
        return systemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROLE.SYSTEM_ID
     *
     * @param systemId the value for ROLE.SYSTEM_ID
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public void setSystemId(String systemId) {
        this.systemId = systemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROLE.DESCRIPTION
     *
     * @return the value of ROLE.DESCRIPTION
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROLE.DESCRIPTION
     *
     * @param description the value for ROLE.DESCRIPTION
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public void setDescription(String description) {
        this.description = description;
    }
}