package com.gfxy.common.portal.entity;

public class RoleResources {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROLE_RESOURCES.REL_ID
     *
     * @mbggenerated Tue May 21 10:11:34 CST 2019
     */
    private String relId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROLE_RESOURCES.ROLE_ID
     *
     * @mbggenerated Tue May 21 10:11:34 CST 2019
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROLE_RESOURCES.TYPE
     *
     * @mbggenerated Tue May 21 10:11:34 CST 2019
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROLE_RESOURCES.RESOURCE_ID
     *
     * @mbggenerated Tue May 21 10:11:34 CST 2019
     */
    private String resourceId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROLE_RESOURCES.REL_ID
     *
     * @return the value of ROLE_RESOURCES.REL_ID
     *
     * @mbggenerated Tue May 21 10:11:34 CST 2019
     */
    public String getRelId() {
        return relId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROLE_RESOURCES.REL_ID
     *
     * @param relId the value for ROLE_RESOURCES.REL_ID
     *
     * @mbggenerated Tue May 21 10:11:34 CST 2019
     */
    public void setRelId(String relId) {
        this.relId = relId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROLE_RESOURCES.ROLE_ID
     *
     * @return the value of ROLE_RESOURCES.ROLE_ID
     *
     * @mbggenerated Tue May 21 10:11:34 CST 2019
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROLE_RESOURCES.ROLE_ID
     *
     * @param roleId the value for ROLE_RESOURCES.ROLE_ID
     *
     * @mbggenerated Tue May 21 10:11:34 CST 2019
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROLE_RESOURCES.TYPE
     *
     * @return the value of ROLE_RESOURCES.TYPE
     *
     * @mbggenerated Tue May 21 10:11:34 CST 2019
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROLE_RESOURCES.TYPE
     *
     * @param type the value for ROLE_RESOURCES.TYPE
     *
     * @mbggenerated Tue May 21 10:11:34 CST 2019
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROLE_RESOURCES.RESOURCE_ID
     *
     * @return the value of ROLE_RESOURCES.RESOURCE_ID
     *
     * @mbggenerated Tue May 21 10:11:34 CST 2019
     */
    public String getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROLE_RESOURCES.RESOURCE_ID
     *
     * @param resourceId the value for ROLE_RESOURCES.RESOURCE_ID
     *
     * @mbggenerated Tue May 21 10:11:34 CST 2019
     */
    public void setResourceId(String resourceId) {
        this.resourceId = resourceId;
    }
}