package com.gfxy.common.portal.entity;

public class Staff {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF.STAFF_ID
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    private String staffId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF.EMAIL
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF.GENDER
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    private Integer gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF.NAME
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF.PHONE
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF.STATE
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF.ORGANIZATION_ID
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    private String organizationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF.IDENTIFICATION_NUMBER
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    private String identificationNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF.PROFESSIONAL_TITLE
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    private String professionalTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF.POSITION
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    private String position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF.TYPE_ID
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    private Integer typeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF.STAFF_ID
     *
     * @return the value of STAFF.STAFF_ID
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public String getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF.STAFF_ID
     *
     * @param staffId the value for STAFF.STAFF_ID
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public void setStaffId(String staffId) {
        this.staffId = staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF.EMAIL
     *
     * @return the value of STAFF.EMAIL
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF.EMAIL
     *
     * @param email the value for STAFF.EMAIL
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF.GENDER
     *
     * @return the value of STAFF.GENDER
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF.GENDER
     *
     * @param gender the value for STAFF.GENDER
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF.NAME
     *
     * @return the value of STAFF.NAME
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF.NAME
     *
     * @param name the value for STAFF.NAME
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF.PHONE
     *
     * @return the value of STAFF.PHONE
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF.PHONE
     *
     * @param phone the value for STAFF.PHONE
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF.STATE
     *
     * @return the value of STAFF.STATE
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF.STATE
     *
     * @param state the value for STAFF.STATE
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF.ORGANIZATION_ID
     *
     * @return the value of STAFF.ORGANIZATION_ID
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public String getOrganizationId() {
        return organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF.ORGANIZATION_ID
     *
     * @param organizationId the value for STAFF.ORGANIZATION_ID
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public void setOrganizationId(String organizationId) {
        this.organizationId = organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF.IDENTIFICATION_NUMBER
     *
     * @return the value of STAFF.IDENTIFICATION_NUMBER
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public String getIdentificationNumber() {
        return identificationNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF.IDENTIFICATION_NUMBER
     *
     * @param identificationNumber the value for STAFF.IDENTIFICATION_NUMBER
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public void setIdentificationNumber(String identificationNumber) {
        this.identificationNumber = identificationNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF.PROFESSIONAL_TITLE
     *
     * @return the value of STAFF.PROFESSIONAL_TITLE
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public String getProfessionalTitle() {
        return professionalTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF.PROFESSIONAL_TITLE
     *
     * @param professionalTitle the value for STAFF.PROFESSIONAL_TITLE
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public void setProfessionalTitle(String professionalTitle) {
        this.professionalTitle = professionalTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF.POSITION
     *
     * @return the value of STAFF.POSITION
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF.POSITION
     *
     * @param position the value for STAFF.POSITION
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public void setPosition(String position) {
        this.position = position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF.TYPE_ID
     *
     * @return the value of STAFF.TYPE_ID
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF.TYPE_ID
     *
     * @param typeId the value for STAFF.TYPE_ID
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }
}