package com.gfxy.common.portal.entity;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.USER_ID
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.LAST_3PWDS
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    private String last3pwds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.LOGIN_NAME
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.LOGIN_SOURCE
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    private String loginSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.PASSWORD
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.STATE
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.USEFUL_TIME
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    private Date usefulTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.STAFF_ID
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    private String staffId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.ROLE_ID
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    private String roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.USER_ID
     *
     * @return the value of USER.USER_ID
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.USER_ID
     *
     * @param userId the value for USER.USER_ID
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.LAST_3PWDS
     *
     * @return the value of USER.LAST_3PWDS
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public String getLast3pwds() {
        return last3pwds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.LAST_3PWDS
     *
     * @param last3pwds the value for USER.LAST_3PWDS
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public void setLast3pwds(String last3pwds) {
        this.last3pwds = last3pwds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.LOGIN_NAME
     *
     * @return the value of USER.LOGIN_NAME
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.LOGIN_NAME
     *
     * @param loginName the value for USER.LOGIN_NAME
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.LOGIN_SOURCE
     *
     * @return the value of USER.LOGIN_SOURCE
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public String getLoginSource() {
        return loginSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.LOGIN_SOURCE
     *
     * @param loginSource the value for USER.LOGIN_SOURCE
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public void setLoginSource(String loginSource) {
        this.loginSource = loginSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.PASSWORD
     *
     * @return the value of USER.PASSWORD
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.PASSWORD
     *
     * @param password the value for USER.PASSWORD
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.STATE
     *
     * @return the value of USER.STATE
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.STATE
     *
     * @param state the value for USER.STATE
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.USEFUL_TIME
     *
     * @return the value of USER.USEFUL_TIME
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public Date getUsefulTime() {
        return usefulTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.USEFUL_TIME
     *
     * @param usefulTime the value for USER.USEFUL_TIME
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public void setUsefulTime(Date usefulTime) {
        this.usefulTime = usefulTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.STAFF_ID
     *
     * @return the value of USER.STAFF_ID
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public String getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.STAFF_ID
     *
     * @param staffId the value for USER.STAFF_ID
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public void setStaffId(String staffId) {
        this.staffId = staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.ROLE_ID
     *
     * @return the value of USER.ROLE_ID
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.ROLE_ID
     *
     * @param roleId the value for USER.ROLE_ID
     *
     * @mbggenerated Fri May 17 14:38:39 CST 2019
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }
}